name: PR Status Check

on: 
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Status Check
        run: echo "Status Check Passed"